### PR TITLE
Events Page

### PR DESCRIPTION
**Pull request by jacob-bw**
- created array of upcoming concerts
- function that prints cards that can expand/contract more details for concerts
- concert card contains a placeholder for button referenced in ticket #17

### CODE REVIEW

**Comment by John-Ryan-Johnson** [comment]
needs to open only correct venue.

**Comment by phillipsja97** [comment]
It looks like when you click on a tour date it opens up all dates instead of that specific date. Needs to open just that specific date.

**Comment by phillipsja97** [comment]
Also, the h1 tag at the top needs to be centered.

**Comment by jacob-bw** [comment]
Updated js to include ${i} on accordion card divs to make id's dynamic and resolve one-click-expands-everything issue

**Comment by ghost** [comment]
👍 +1

**Pull request merged**
